- name: Get Apache2 configuration file path
  ansible.builtin.shell: apachectl -V
  register: apache_config_file
  failed_when: apache_config_file.rc != 0
  changed_when: false

- name: Extract Apache2 configuration file path
  set_fact:
    apache_config_file_path: "{{ apache_config_file.stdout | regex_search('SERVER_CONFIG_FILE=\"([^\"]+)\"', '\\1') | first }}"

- name: Extract Apache2 configuration root path
  set_fact:
    apache_root_config_path: "{{ apache_config_file.stdout | regex_search('HTTPD_ROOT=\"([^\"]+)\"', '\\1') | first }}"

- name: Extract Apache2 configuration directory
  set_fact:
    apache_config_path: "{{ apache_root_config_path }}/{{ apache_config_file_path }}"

- name: Display Apache2 configuration directory
  debug:
    msg: "Apache2 configuration directory is: {{ apache_config_path }}"