---
- name: Move webserver to container
  hosts: localhost
  gather_facts: true
  become: true

  vars:
    rootless_user: containers

  roles:
    - name: identify_web_service
    # - name: find_website_content
    # - name: prepare_container_environment
    #   vars:
    #     apache2_content_dirs: "{{ document_roots }}"
    - name: identify_web_service_content
