- name: Run rootless apache2 container as {{ rootless_user }} user
  containers.podman.podman_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    state: started
    restart_policy: always
    ports:
      - "8080:80"
    volumes:
      - "/etc/apache2:/etc/apache2"  # Mount Apache configuration directory
      - "/var/www:/var/www" 
