- name: Create ports mapping list
  set_fact:
    webservice_ports_mappings: "{{ webservice_ports | map('regex_replace', '(\\d+)', '\\1:\\1') | list }}"

- name: debug
  debug:
    msg: "{{ webservice_ports_mappings }}"


- name: Pull ubuntu:22.04 image
  containers.podman.podman_image:
    name: docker.io/library/ubuntu
    tag: "22.04"

- name: Create a container from the ubuntu:22.04 image
  containers.podman.podman_container:
    name: ubuntu_apache2_container
    image: docker.io/library/ubuntu
    state: started
    command: sleep infinity  # Keep the container running

- name: Install updates and apache2 package inside the container
  containers.podman.podman_container_exec:
    container: ubuntu_apache2_container
    cmd: |
      apt-get update -y
      apt-get upgrade -y
      apt-get install -y apache2

- name: Commit the modified container to a new image
  containers.podman.podman_image:
    name: my_custom_ubuntu_apache
    tag: latest
    source: container
    container: ubuntu_apache2_container

- name: Stop the container
  containers.podman.podman_container:
    name: ubuntu_apache2_container
    state: stopped

- name: Remove the container
  containers.podman.podman_container:
    name: my_podman_container
    state: absent

# - name: Run rootless apache2 container as {{ rootless_user }} user
#   containers.podman.podman_container:
#     name: "{{ container_name }}"
#     image: "{{ container_image }}"
#     state: started
#     restart_policy: always
#     ports: "{{ webservice_ports_mappings }}"
#     volumes:
#       - /etc/apache2/apache2.conf:/usr/local/apache2/conf/httpd.conf
#       - "/etc/apache2:/etc/apache2"
#       - "/var/www:/var/www" 
