- name: Create ports mapping list
  set_fact:
    webservice_ports_mappings: "{{ webservice_ports | map('regex_replace', '(\\d+)', '\\1:\\1') | list }}"

- name: debug
  debug:
    msg: "{{ webservice_ports_mappings }}"

- name: Pull {{ ubuntu_container_image }} image
  containers.podman.podman_image:
    name: "{{ ubuntu_container_image }}"

- name: Create directory for Dockerfile
  file:
    path: "{{ ansible_env.HOME }}/apache2"
    state: directory
    mode: '0755'

- name: Create Dockerfile from template
  template:
    src: templates/Dockerfile_apache2.j2
    dest: "{{ ansible_env.HOME }}/apache2/Dockerfile"
    mode: '0755'

- name: Create entrypoint.sh from template
  template:
    src: templates/entrypoint_apache2.sh
    dest: "{{ ansible_env.HOME }}/apache2/entrypoint.sh"
    mode: '0755'

- name: Build container image
  command: 
    cmd: podman build -t {{ custom_apache2_container_image }} .
    chdir: "{{ ansible_env.HOME }}/apache2"
  become_user: "{{ ansible_env.HOME }}"

- name: Stop apache2 service on host os
  systemd:
    name: apache2
    state: stopped
    enabled: false


- name: Run apache2 container in userns
  containers.podman.podman_container:
    name: "{{ apache2_container_name }}"
    image: "{{ custom_apache2_container_image }}"
    state: started
    restart_policy: always
    ports: "{{ webservice_ports_mappings }}"
    detach: true
    interactive: true
    tty: true
    userns: auto

- name: Remove not used images
  command:
    cmd: podman image prune --force


