- name: Create ports mapping list
  set_fact:
    webservice_ports_mappings: "{{ webservice_ports | map('regex_replace', '(\\d+)', '\\1:\\1') | list }}"

- name: debug
  debug:
    msg: "{{ webservice_ports_mappings }}"

- name: Pull {{ ubuntu_container_image }} image
  containers.podman.podman_image:
    name: "{{ ubuntu_container_image }}"

- name: Create directory for Dockerfile
  file:
    path: /home/{{ rootless_user }}/nginx
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: '0755'

- name: Create Dockerfile from template
  template:
    src: templates/Dockerfile.j2
    dest: /home/{{ rootless_user }}/nginx/Dockerfile
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: '0755'

- name: Create entrypoint.sh from template
  template:
    src: templates/entrypoint.sh
    dest: /home/{{ rootless_user }}/nginx/entrypoint.sh
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: '0755'

- name: Enable lingering for rootless user
  command:
    cmd: loginctl enable-linger {{ rootless_user }}

- name: Build container image
  command: 
    cmd: podman build -t {{ custom_nginx_container_image }} .
    chdir: /home/{{ rootless_user }}/nginx
  become_user: "{{ rootless_user }}"

- name: Stop nginx service on host os
  systemd:
    name: nginx
    state: stopped
    enabled: false


- name: Run nginx container in userns
  containers.podman.podman_container:
    name: "{{ nginx_container_name }}"
    image: "{{ custom_nginx_container_image }}"
    state: started
    restart_policy: always
    ports: "{{ webservice_ports_mappings }}"
    detach: true
    interactive: true
    tty: true
    userns: auto

- name: Remove not used images
  command:
    cmd: podman image prune --force
  become_user: "{{ rootless_user }}"


