- name: Create ports mapping list
  set_fact:
    webservice_ports_mappings: "{{ webservice_ports | map('regex_replace', '(\\d+)', '\\1:\\1') | list }}"

- name: debug
  debug:
    msg: "{{ webservice_ports_mappings }}"

- name: Pull {{ ubuntu_container_image }} image
  containers.podman.podman_image:
    name: "{{ ubuntu_container_image }}"

- name: Create directory for Dockerfile
  file:
    path: "{{ ansible_env.HOME }}/nginx"
    state: directory
    mode: '0755'

- name: Create Dockerfile from template
  template:
    src: templates/Dockerfile_nginx.j2
    dest: "{{ ansible_env.HOME }}/nginx/Dockerfile"
    mode: '0755'

- name: Create entrypoint.sh from template
  template:
    src: templates/entrypoint_nginx.sh
    dest: "{{ ansible_env.HOME }}/nginx/entrypoint.sh"
    mode: '0755'

- name: Build container image
  command: 
    cmd: podman build -t {{ custom_nginx_container_image }} .
    chdir: "{{ ansible_env.HOME }}/nginx"

- name: Stop nginx service on host os
  systemd:
    name: nginx
    state: stopped
    enabled: false


- name: Run nginx container in userns
  containers.podman.podman_container:
    name: "{{ nginx_container_name }}"
    image: "{{ custom_nginx_container_image }}"
    state: started
    restart_policy: always
    ports: "{{ webservice_ports_mappings }}"
    detach: true
    interactive: true
    tty: true
    userns: auto

- name: Remove not used images
  command:
    cmd: podman image prune --force



