nginx_container_name: nginx_ubuntu
custom_nginx_container_image: docker.io/library/nginx_ubuntu:22.04
nginx_config_path: "{{ notdefined | mandatory(msg='This variable is required.') }}"
nginx_content_path: "{{ notdefined | mandatory(msg='This variable is required.') }}"
nginx_ssl_certs_path: "{{ nginx_sslcertificatefile_path }}"

