- name: Search for DocumentRoot directive in Apache2 config files
  command: grep -r "DocumentRoot" /etc/apache2/sites-available/
  register: apache_documentroot
  failed_when: false

- name: Extract and filter unique DocumentRoot paths
  set_fact:
    document_roots: "{{ apache_documentroot.stdout_lines | select('search', 'DocumentRoot') | map('regex_replace', '.*DocumentRoot\\s+(.*)', '\\1') | unique | list }}"

- name: Display unique DocumentRoot paths
  debug:
    msg: "{{ document_roots }}"