FROM {{ ubuntu_container_image }}

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y nginx

COPY /backup/ /

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

{% for port in webservice_ports %}
EXPOSE {{ port }}
{% endfor %}

ENTRYPOINT ["/entrypoint.sh"]
