FROM {{ ubuntu_container_image }}

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y apache2
RUN apt-get install -y systemctl

{% for module in apache2_enabled_modules %}
RUN apt-get install -y {{ module }}
{% endfor %}

COPY {{ apache2_config_path }} {{ apache2_config_path }}
{% for dir in apache2_content_path %}
COPY {{ dir }} {{ dir }}
{% endfor %}

{% for port in webservice_ports %}
EXPOSE {{ port }}
{% endfor %}

CMD ["systemctl", "enable", "--now" "apache2"]