FROM {{ ubuntu_container_image }}



RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y apache2


COPY {{ apache2_config_path }} {{ apache2_config_path }}

{% for dir in apache2_content_path %}
COPY {{ dir }} {{ dir }}
{% endfor %}

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

{% for port in webservice_ports %}
EXPOSE {{ port }}
{% endfor %}

ENTRYPOINT ["/entrypoint.sh"]
