- name: Find all .conf and .load files under /etc/apache2/
  find:
    paths: "/etc/apache2"
    recurse: yes
    patterns: "*.conf"
  register: conf_files

- name: Find all .load files under /etc/apache2/
  find:
    paths: "/etc/apache2"
    recurse: yes
    patterns: "*.load"
  register: load_files

- name: Combine the results and display all files
  set_fact:
    all_files: "{{ conf_files.files + load_files.files }}"

- name: Display all the matching files
  debug:
    msg: "{{ all_files | map(attribute='path') | list }}"