- name: Run apache2ctl -V command
  command: apache2ctl -V
  register: apache_output

- name: Parse Server Root from apache2ctl output
  set_fact:
    server_root: "{{ apache_output.stdout | regex_search('HTTPD_ROOT=\"([^\"]+)\"') }}"

- name: Parse Suexec Bin from apache2ctl output
  set_fact:
    suexec_bin: "{{ apache_output.stdout | regex_search('SUEXEC_BIN=\"([^\"]+)\"') }}"

- name: Parse Default Error Log from apache2ctl output
  set_fact:
    error_log: "{{ apache_output.stdout | regex_search('DEFAULT_ERRORLOG=\"([^\"]+)\"') }}"

- name: Show parsed values
  debug:
    msg:
      - "Server Root: {{ server_root }}"
      - "Suexec Bin: {{ suexec_bin }}"
      - "Error Log: {{ error_log }}"