- name: Find all .conf and .load files under /etc/apache2/
  find:
    paths: "/etc/apache2"
    recurse: yes
    patterns: "*.conf"
  register: conf_files

- name: Find all .load files under /etc/apache2/
  find:
    paths: "/etc/apache2"
    recurse: yes
    patterns: "*.load"
  register: load_files

- name: Combine the results into a single list
  set_fact:
    all_files: "{{ conf_files.files + load_files.files }}"

- name: Read the content of each file
  slurp:
    src: "{{ item.path }}"
  loop: "{{ all_files }}"
  register: file_contents

- name: Extract paths from the file content excluding comment lines
  set_fact:
    paths_found: "{{ paths_found | default([]) + (item.content | b64decode | splitlines() | selectattr('startswith', '#', invert=true) | map('regex_replace', '\\s*#.*$', '') | selectattr('search', '^/|^\\w') ) }}"
  loop: "{{ file_contents.results }}"

- name: Display all found paths
  debug:
    msg: "{{ paths_found | unique }}"

# - name: Find all .conf and .load files under /etc/apache2/
#   find:
#     paths: "/etc/apache2"
#     recurse: yes
#     patterns: "*.conf"
#   register: conf_files

# - name: Find all .load files under /etc/apache2/
#   find:
#     paths: "/etc/apache2"
#     recurse: yes
#     patterns: "*.load"
#   register: load_files

# - name: Combine the results and display all files
#   set_fact:
#     all_files: "{{ conf_files.files + load_files.files }}"

# - name: Display all the matching files
#   debug:
#     msg: "{{ all_files | map(attribute='path') | list }}"