- name: Slurp the file
  slurp:
    src: "{{ file_path }}"
  register: slurped_file

- name: Extract and clean the content after line starting with search_string
  set_fact:
    result: "{{ (slurped_file.content | b64decode).split('\n') | selectattr('startswith', search_string) | map('regex_replace', '^' + search_string + '\\s*', '') | first | regex_replace('\\s+', '') }}"

- name: Display the result
  debug:
    msg: "{{ result }}"