- name: Run apache2ctl -V command
  command: apache2ctl -V
  register: apache_output

- name: Parse HTTPD_ROOT from apache2ctl output
  set_fact:
    httpd_root: "{{ apache_output.stdout | regex_search('HTTPD_ROOT=\"([^\"]+)\"') | first }}"

- name: Parse SERVER_CONFIG_FILE from apache2ctl output
  set_fact:
    server_config_file: "{{ apache_output.stdout | regex_search('SERVER_CONFIG_FILE=\"([^\"]+)\"') | first }}"

- name: Show parsed values
  debug:
    msg:
      - "{{ httpd_root }}"
      - "{{ server_config_file }}"