- name: Run apache2ctl -V command
  command: apache2ctl -V
  register: apache_output

- name: Parse Server Root from apache2ctl output
  set_fact:
    server_root: "{{ apache_output.stdout | regex_search('HTTPD_ROOT=\"(.*?)\"') }}"

- name: PRint
  debug:
    msg: "server_root"