pgsql_host_port: 5432
pgsql_user_workdir: /tmp/psql
pgsql_backup_filename: database_dump.sql
pgsql_backup_path: "{{ pgsql_user_workdir }}/{{ pgsql_backup_filename }}"
pgsql_docker_image: docker.io/rapidfort/postgresql
#docker.io/library/postgres:{{ pgsql_version }}
pgsql_custom_image: docker.io/library/postgres_custom
pgsql_container_name: postgresql
pgsql_podman_volume_name: postgresql_pv
pgsql_uid_mapping_start: 100000