- name: Get Apache2 configuration file path
  ansible.builtin.shell: apachectl -V
  register: apache2_config_file
  failed_when: apache2_config_file.rc != 0
  changed_when: false

# Apache2 apache2.conf config path
- name: Extract Apache2 configuration root path
  set_fact:
    apache2_root_path: "{{ apache2_config_file.stdout | regex_search('HTTPD_ROOT=\"([^\"]+)\"', '\\1') | first }}"

- name: Extract Apache2 configuration file path
  set_fact:
    apache2_config_file_path: "{{ apache2_root_path }}/{{ apache2_config_file.stdout | regex_search('SERVER_CONFIG_FILE=\"([^\"]+)\"', '\\1') | first }}"

- name: Display Apache2 configuration directory
  debug:
    msg: "Apache2 configuration directory is: {{ apache2_config_file_path }}"

# DocumentRoot in apache2
- name: Search for DocumentRoot directive in Apache2 config files
  command: grep -r "DocumentRoot" {{ apache2_root_path }}/sites-available/ {{ apache2_root_path }}/sites-enabled/
  register: apache2_documentroot_otput
  failed_when: false

- name: Extract and filter unique DocumentRoot paths
  set_fact:
    apache2_document_roots: "{{ apache2_documentroot_otput.stdout_lines | select('search', 'DocumentRoot') | map('regex_replace', '.*DocumentRoot\\s+(.*)', '\\1') | unique | list }}"

- name: Display unique DocumentRoot paths
  debug:
    msg: "{{ apache2_document_roots }}"

# SSLCertificateFile
- name: Search for SSLCertificateFile  directive in Apache2 config files
  command: grep -r "SSLCertificateFile" {{ apache2_root_path }}/sites-available/ {{ apache2_root_path }}/sites-enabled/
  register: apache2_sslcrtificatefile_otput
  failed_when: false

- name: Extract and filter unique SSLCertificateFile paths
  set_fact:
    apache2_sslcertificatefile_path: "{{ apache2_sslcrtificatefile_otput.stdout_lines | select('search', 'SSLCertificateFile') | map('regex_replace', '.*SSLCertificateFile\\s+(.*)', '\\1') | unique | list }}"

# SSLCertificateKeyFile
- name: Search for SSLCertificateKeyFile directive in Apache2 config files
  command: grep -r "SSLCertificateKeyFile " {{ apache2_root_path }}/sites-available/ {{ apache2_root_path }}/sites-enabled/
  register: apache2_sslcertificatekeyfile_otput
  failed_when: false

- name: Extract and filter unique SSLCertificateKeyFile paths
  set_fact: 
    apache2_sslcertificatekeyfile_path:  "{{ apache2_sslcertificatekeyfile_otput.stdout_lines | select('search', 'SSLCertificateKeyFile') | map('regex_replace', '.*SSLCertificateKeyFile\\s+(.*)', '\\1') | unique | list }}"

- name: Set unique apache2 SSL files path
  set_fact:
    apache2_ssl_certs_path_combined: "{{ apache2_sslcertificatekeyfile_path + apache2_sslcertificatefile_path | list | unique }}"

- name: Filter list
  set_fact:
      apache2_ssl_certs_path: '{{ apache2_ssl_certs_path_combined | select("match", "^/[^# \t]*$") | list | unique }}'

- name: Display unique SSLCertificateFile paths
  debug:
    msg: "{{ apache2_ssl_certs_path }}"

# Backup

- name: Create directory for apache2 backup in {{ ansible_env.HOME }} home directory
  file:
    path: "{{ ansible_env.HOME }}/apache2/backup"
    state: directory
    mode: '0755'

- name: Backup apache2 config recursively while preserving file permissions
  ansible.builtin.copy:
    src: "{{ apache2_root_path }}/"
    dest: "{{ ansible_env.HOME }}/apache2/backup{{ apache2_root_path }}"
    mode: preserve
    force: true

- name: Backup apache2 content recursively while preserving file permissions
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ ansible_env.HOME }}/apache2/backup{{ item }}"
    mode: preserve
    force: true
  loop: "{{ apache2_document_roots }}"
 
- name: Create the target directories dynamically
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/apache2/backup/{{ item | regex_replace('^/+', '') | regex_replace('/[^/]+$', '') }}"
    state: directory
    mode: '0755'
  loop: "{{ apache2_ssl_certs_path }}"
  ignore_errors: true

- name: Backup apache2 certificates recursively while preserving file permissions
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ ansible_env.HOME }}/apache2/backup{{ item }}"
    mode: preserve
    force: true
  loop: "{{ apache2_ssl_certs_path }}"
  ignore_errors: true
