- name: Get nginx configuration file path
  ansible.builtin.shell: nginx -V
  register: nginx_config_file
  failed_when: nginx_config_file.rc != 0
  changed_when: false

- name: Extract nginx configuration root path
  set_fact:
    nginx_root_path: "{{ nginx_config_file.stdout | regex_search('--conf-path=([^\s]+)', '\\1') | first }}"

# - name: Extract nginx configuration file path
#   set_fact:
#     nginx_config_file_path: "{{ nginx_root_path }}/{{ nginx_config_file.stdout | regex_search('SERVER_CONFIG_FILE=\"([^\"]+)\"', '\\1') | first }}"

- name: Display nginx configuration directory
  debug:
    msg: "nginx configuration directory is: {{ nginx_root_path }}"