FROM {{ pgsq_docker_image }}

# Set environment variables (optional, you can change this)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=yourpassword
ENV POSTGRES_DB=yourdbname


COPY {{ pgsql_backup_filename }} /docker-entrypoint-initdb.d/

# The database dump will be automatically restored during the container's first initialization
# The /docker-entrypoint-initdb.d/ directory is special and any script or dump files placed here are run during container startup