- name: Include Ubuntu specific defaults
  include_vars: defaults/apache2.yaml
  when: web_service_name == "apache2"

- name: Include tasks for apache2 webservice
  include_tasks: apache2.yaml
  when: web_service_name == "apache2"
