- name: Install Podman and dependencies
  apt:
    name:
      - podman
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - uidmap
      - dbus-user-session
    state: present
    update_cache: yes

- name: Create a user for rootless containers
  user:
    name: containers
    state: present
    create_home: yes
    shell: /bin/bash

- name: Run rootless HTTPD container as podmanuser
  community.podman.podman_container:
    name: httpd-container
    image: httpd
    state: started
    restart_policy: always
    ports:
      - "8080:80"
  become_user: containers