- name: Gather facts about services
  service_facts:

# Apache2
- name: Check if apache2 is installed and running
  set_fact:
    apache2_started: "{{ 'true' if ansible_facts.services['apache2'].state == 'running' else 'false' }}"
  when: "'apache2' in ansible_facts.services"

- name: Set web service name to Apache
  set_fact:
    web_service_name: "apache2"
  when: apache2_started is defined and apache2_started

# Nginx

- name: Check if nginx is installed and running
  set_fact:
    nginx_started: "{{ 'true' if ansible_facts.services['nginx'].state == 'running' else 'false' }}"
  when: "'nginx' in ansible_facts.services"

- name: Set web service name to Apache
  set_fact:
    web_service_name: "nginx"
  when: nginx_started is defined and nginx_started

# Nodejs

- name: Check if Node.js is running
  command: ps aux | grep '[n]ode'
  register: node_process
  changed_when: false
  failed_when: false

- name: Ensure Node.js is running
  debug:
    msg: "Node.js is running"
  when: node_process.stdout != ""
  
- name: Ensure Node.js is not running
  debug:
    msg: "Node.js is not running"
  when: node_process.stdout == ""




# - name: Check if Nginx is installed
#   shell: dpkg -l | grep nginx
#   register: nginx_check
#   ignore_errors: yes

# - name: Set web service name to Nginx
#   set_fact:
#     web_service_name: "nginx"
#   when: nginx_check.rc == 0

# - name: Check if Lighttpd is installed
#   shell: dpkg -l | grep lighttpd
#   register: lighttpd_check
#   ignore_errors: yes

# - name: Set web service name to Lighttpd
#   set_fact:
#     web_service_name: "lighttpd"
#   when: lighttpd_check.rc == 0

# - name: Display the detected web service binary name
#   debug:
#     msg: "Detected web service binary name: {{ web_service_name }}"

- name: Print web service name
  debug:
    msg: "Web service {{ web_service_name }} is running"
  when: web_service_name is defined


- name: Fail playbook if no web service detected
  debug:
    fail: "No web service is installed."
  when: web_service_name is not defined